eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8082
spring:
  application:
    name: restaurantservice
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
